### ISSUE TITLE
AD0001 CopiedSpinLockAnalyzer NullReferenceException

### ISSUE THREAD

**Issue by nnpcYvIVl** [smartanalyzers/MultithreadingAnalyzer#1]
See attached stacktrace.

```
Warning	AD0001	Analyzer 'SmartAnalyzers.MultithreadingAnalyzer.CopiedSpinLockAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
'Exception occurred with following context:
SyntaxTree: \Immutable\Immutable\System\Collections\Immutable\ImmutableHashSet_1.cs
SyntaxNode: kv [ParameterSyntax]@[1610..1612) (31,94)-(31,96)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartAnalyzers.MultithreadingAnalyzer.CopiedSpinLockAnalyzer.AnalyzeParameter(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by cezarypiatek** [comment]
Hi,
Thanks for reporting this issue. Would you mind to attach te code that causes this error?

**Comment by nnpcYvIVl** [comment]
@cezarypiatek See attached.

[ImmutableHashSet_1.zip](https://github.com/smartanalyzers/MultithreadingAnalyzer/files/3571441/ImmutableHashSet_1.zip)

**Comment by cezarypiatek** [comment]
Ok, I found the culprit. A new version 1.0.10 should be available on the NuGet.  Please let me know if that fixed the problem for you.

**Comment by nnpcYvIVl** [comment]
@cezarypiatek That fixed it, thanks for the quick turnaround!
